version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm i
      - run: npm run test:ci
  deploy:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo ${REACT_APP_STAGE}
      - run: npm i
      - run: REACT_APP_STAGE=${REACT_APP_STAGE} npm run build
      - run: npm i firebase-tools
      - run: ./node_modules/firebase-tools/lib/bin/firebase.js deploy --token ${FIREBASE_TOKEN}

workflows:
  version: 2
  run:
    jobs:
      - deploy:
          context: sandbox
          filters:
            branches:
              only:
                - uat
      - deploy:
          context: production
          filters:
            branches:
              only:
                - master
